### Base variables (change the port if needed)
@baseUrl = http://localhost:3000
@json = application/json

GET {{baseUrl}}/api/ping

### GET all expenses
GET {{baseUrl}}/api/expenses

### Create a new expense
# @name createExpense
POST {{baseUrl}}/api/expenses
Content-Type: {{json}}

{
  "id": "{{$guid}}",
  "date": "{{$datetime iso8601}}",
  "description": "REST Client test",
  "payer": "Alice",
  "amount": 12.34
}

### POST reset expenses to initial data
POST {{baseUrl}}/api/expenses/reset
